/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.vistas;

import sistema.datos.reportesDatos;

/**
 *
 * @author Usuario
 */
public class ReportesFrame extends javax.swing.JFrame {
    //instancia a reportes
    reportesDatos objReporte =new reportesDatos();
    
    /**
     * Creates new form ReportesFrame
     */
    public ReportesFrame() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(1);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        pantallaContenedor = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        reporteVentasRangos = new javax.swing.JToggleButton();
        reporteVentasDiaria = new javax.swing.JToggleButton();
        reporteGastos = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pantallaContenedorLayout = new javax.swing.GroupLayout(pantallaContenedor);
        pantallaContenedor.setLayout(pantallaContenedorLayout);
        pantallaContenedorLayout.setHorizontalGroup(
            pantallaContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        pantallaContenedorLayout.setVerticalGroup(
            pantallaContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(85, 95, 128));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        reporteVentasRangos.setBackground(new java.awt.Color(185, 174, 174));
        buttonGroup1.add(reporteVentasRangos);
        reporteVentasRangos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reporteVentasRangos.setForeground(new java.awt.Color(0, 0, 0));
        reporteVentasRangos.setText("Reporte de Ventas");
        reporteVentasRangos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteVentasRangosActionPerformed(evt);
            }
        });

        reporteVentasDiaria.setBackground(new java.awt.Color(185, 174, 174));
        buttonGroup1.add(reporteVentasDiaria);
        reporteVentasDiaria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reporteVentasDiaria.setForeground(new java.awt.Color(0, 0, 0));
        reporteVentasDiaria.setText("Reporte de productos");
        reporteVentasDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteVentasDiariaActionPerformed(evt);
            }
        });

        reporteGastos.setBackground(new java.awt.Color(185, 174, 174));
        buttonGroup1.add(reporteGastos);
        reporteGastos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reporteGastos.setForeground(new java.awt.Color(0, 0, 0));
        reporteGastos.setText("Reporte de gastos");
        reporteGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteGastosActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(128, 48, 48));
        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reporteGastos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporteVentasDiaria, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(reporteVentasRangos, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(reporteVentasRangos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reporteVentasDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reporteGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantallaContenedor)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pantallaContenedor)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();

        setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void reporteGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteGastosActionPerformed
        // TODO add your handling code here:
        if (objGastos == null){
            objGastos = new reporteGastos();
            pantallaContenedor.add(objGastos);
            pantallaContenedor.getDesktopManager().maximizeFrame(objGastos);
            objGastos.setVisible(true);
        }
        else{
            pantallaContenedor.getDesktopManager().maximizeFrame(objGastos);

        }

    }//GEN-LAST:event_reporteGastosActionPerformed

    private void reporteVentasDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteVentasDiariaActionPerformed
        // TODO add your handling code here:
        if (objProducto == null){
            objProducto = new reporteProductos();
            pantallaContenedor.add(objProducto);
            pantallaContenedor.getDesktopManager().maximizeFrame(objProducto);
            objProducto.setVisible(true);
        }
        else{
            pantallaContenedor.getDesktopManager().maximizeFrame(objProducto);

        }
    }//GEN-LAST:event_reporteVentasDiariaActionPerformed

    private void reporteVentasRangosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteVentasRangosActionPerformed
        // TODO add your handling code here:
        if (objVenta == null){
            objVenta = new reporteVentas();
            pantallaContenedor.add(objVenta);
            pantallaContenedor.getDesktopManager().maximizeFrame(objVenta);
            objVenta.setVisible(true);
        }
        else{
            pantallaContenedor.getDesktopManager().maximizeFrame(objVenta);

        }

    }//GEN-LAST:event_reporteVentasRangosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    reporteVentas objVenta=null;
    reporteProductos objProducto =null;    reporteGastos objGastos = null;
    int xx,xy;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane pantallaContenedor;
    private javax.swing.JToggleButton reporteGastos;
    private javax.swing.JToggleButton reporteVentasDiaria;
    private javax.swing.JToggleButton reporteVentasRangos;
    // End of variables declaration//GEN-END:variables
}
